-- A least-privilege login for the PUBLIC dashboard.
--
-- The dashboard runs with whatever credentials Streamlit Cloud holds. Running it
-- as ACCOUNTADMIN would put an admin login behind a public URL. This role can:
--   * use one warehouse,
--   * read CORE and ANALYTICS (tables and views, including future ones dbt
--     creates),
--   * and write exactly one table: CORE.dashboard_leg_flag, where viewers flag a
--     leg as not on the site.
--
-- Run as ACCOUNTADMIN, choosing the password yourself where marked. Never commit
-- the password.

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS ARBIBET_DASHBOARD;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ARBIBET_DASHBOARD;
GRANT USAGE ON DATABASE ARBIBET_CAPSTONE TO ROLE ARBIBET_DASHBOARD;
GRANT USAGE ON SCHEMA ARBIBET_CAPSTONE.CORE TO ROLE ARBIBET_DASHBOARD;
GRANT USAGE ON SCHEMA ARBIBET_CAPSTONE.ANALYTICS TO ROLE ARBIBET_DASHBOARD;

GRANT SELECT ON ALL TABLES IN SCHEMA ARBIBET_CAPSTONE.CORE TO ROLE ARBIBET_DASHBOARD;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ARBIBET_CAPSTONE.CORE TO ROLE ARBIBET_DASHBOARD;
GRANT SELECT ON ALL TABLES IN SCHEMA ARBIBET_CAPSTONE.ANALYTICS TO ROLE ARBIBET_DASHBOARD;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ARBIBET_CAPSTONE.ANALYTICS TO ROLE ARBIBET_DASHBOARD;
GRANT SELECT ON ALL VIEWS IN SCHEMA ARBIBET_CAPSTONE.ANALYTICS TO ROLE ARBIBET_DASHBOARD;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ARBIBET_CAPSTONE.ANALYTICS TO ROLE ARBIBET_DASHBOARD;

-- The one write.
GRANT INSERT, UPDATE ON TABLE ARBIBET_CAPSTONE.CORE.dashboard_leg_flag TO ROLE ARBIBET_DASHBOARD;

CREATE USER IF NOT EXISTS ARBIBET_DASHBOARD
    PASSWORD = '<choose a strong password>'
    DEFAULT_ROLE = ARBIBET_DASHBOARD
    DEFAULT_WAREHOUSE = COMPUTE_WH
    MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE ARBIBET_DASHBOARD TO USER ARBIBET_DASHBOARD;
